[build]
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# 👇 Erzwingt, dass die Startseite immer die Landingpage ist
[[redirects]]
  from = "/"
  to   = "/index.html"
  status = 200

# Slash-Normalisierung nur fürs Admin
[[redirects]]
  from = "/admin"
  to   = "/admin/"
  status = 301
