[build]
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/admin"
  to   = "/admin/"
  status = 301
  
[[redirects]]
  from = "/"
  to   = "/index.html"
  status = 200
